import { Book } from './types';

export const GENRES = [
    'Fiction',
    'Science Fiction',
    'Fantasy',
    'Mystery',
    'Thriller',
    'Romance',
    'Historical Fiction',
    'Literary Fiction',
    'Non-Fiction',
    'Biography',
    'Self-Help',
    'Business',
    'Science',
    'History',
    'Philosophy',
    'Psychology',
    'Young Adult',
    'Children',
];

export const MOODS = [
    { name: 'Adventurous', emoji: '🗺️', color: 'from-orange-500 to-red-500' },
    { name: 'Contemplative', emoji: '🤔', color: 'from-purple-500 to-blue-500' },
    { name: 'Joyful', emoji: '😊', color: 'from-yellow-400 to-pink-400' },
    { name: 'Mysterious', emoji: '🔍', color: 'from-gray-700 to-purple-900' },
    { name: 'Romantic', emoji: '💕', color: 'from-pink-400 to-rose-600' },
    { name: 'Thrilling', emoji: '⚡', color: 'from-red-600 to-orange-600' },
    { name: 'Peaceful', emoji: '🌊', color: 'from-blue-300 to-teal-400' },
    { name: 'Inspiring', emoji: '✨', color: 'from-amber-400 to-orange-500' },
    { name: 'Dark', emoji: '🌑', color: 'from-gray-800 to-black' },
    { name: 'Whimsical', emoji: '🎨', color: 'from-purple-400 to-pink-500' },
    { name: 'Nostalgic', emoji: '📸', color: 'from-amber-500 to-brown-500' },
    { name: 'Energetic', emoji: '⚡', color: 'from-green-400 to-cyan-500' },
    { name: 'Cozy', emoji: '☕', color: 'from-orange-300 to-amber-400' },
    { name: 'Epic', emoji: '⚔️', color: 'from-red-700 to-purple-700' },
    { name: 'Melancholic', emoji: '🌧️', color: 'from-gray-500 to-blue-600' },
    { name: 'Curious', emoji: '🔬', color: 'from-cyan-500 to-blue-600' },
    { name: 'Witty', emoji: '😄', color: 'from-yellow-500 to-green-500' },
    { name: 'Reflective', emoji: '🪞', color: 'from-indigo-400 to-purple-500' },
    { name: 'Hopeful', emoji: '🌅', color: 'from-orange-400 to-pink-400' },
    { name: 'Magical', emoji: '✨', color: 'from-purple-500 to-pink-600' },
];

export const MOCK_BOOKS: Book[] = [
    {
        id: '1',
        title: 'Muna Madan',
        author: 'Laxmi Prasad Devkota',
        coverUrl: '/books/muna-madan.png',
        rating: 4.9,
        reviewCount: 15420,
        price: { hardcover: 500, paperback: 350, ebook: 150, audiobook: 100 },
        formats: ['hardcover', 'paperback', 'ebook', 'audiobook'],
        readingTime: 120,
        genres: ['Poetry', 'Tragedy', 'Romance'],
        description: 'Muna Madan is a short epic narrative poem by Laxmi Prasad Devkota. It is one of the most popular works in Nepali literature.',
        excerpt: 'Ishwar taila banayera, ke garyou manchhe lai? Ke garyou manchhe lai? ...',
        publishDate: '1936-01-01',
        publisher: 'Sajha Prakashan',
        pages: 60,
        isbn: '978-9937209876',
        tags: ['Classic', 'Poetry', 'Must Read'],
        isBestseller: true,
        isNew: false,
        mood: ['Melancholic', 'Romantic', 'Inspiring'],
    },
    {
        id: '2',
        title: 'Palpasa Cafe',
        author: 'Narayan Wagle',
        coverUrl: '/books/palpasa-cafe.png',
        rating: 4.7,
        reviewCount: 8924,
        price: { hardcover: 800, paperback: 550, ebook: 300 },
        formats: ['hardcover', 'paperback', 'ebook'],
        readingTime: 350,
        genres: ['Fiction', 'Historical', 'War'],
        description: 'Palpasa Cafe tells the story of an artist, Drishya, during the height of the Nepali Civil War. It explores the effects of the war on ordinary people.',
        excerpt: 'Drishya sat in the cafe, watching the rain wash away the dust of Kathmandu...',
        publishDate: '2005-01-01',
        publisher: 'Nepalaya',
        pages: 245,
        isbn: '978-9937802107',
        tags: ['Civil War', 'Art', 'Bestseller'],
        isBestseller: true,
        isNew: false,
        mood: ['Contemplative', 'Melancholic', 'Reflective'],
    },
    {
        id: '3',
        title: 'Karnali Blues',
        author: 'Buddhisagar',
        coverUrl: '/books/karnali-blues.png',
        rating: 4.8,
        reviewCount: 12500,
        price: { hardcover: 750, paperback: 450, ebook: 250 },
        formats: ['hardcover', 'paperback', 'ebook'],
        readingTime: 400,
        genres: ['Fiction', 'Coming of Age', 'Regional'],
        description: 'Karnali Blues is a story about a young boy\'s relationship with his father, set against the backdrop of the Karnali region.',
        excerpt: 'My father\'s face is like a map of Karnali...',
        publishDate: '2010-08-01',
        publisher: 'FinePrint',
        pages: 400,
        isbn: '978-9937828855',
        tags: ['Fatherhood', 'Regional', 'Touching'],
        isBestseller: true,
        isNew: false,
        mood: ['Nostalgic', 'Emotional', 'Hopeful'],
    },
    {
        id: '4',
        title: 'Seto Dharti',
        author: 'Amar Neupane',
        coverUrl: '/books/seto-dharti.png',
        rating: 4.6,
        reviewCount: 9800,
        price: { hardcover: 650, paperback: 400, ebook: 200 },
        formats: ['hardcover', 'paperback', 'ebook'],
        readingTime: 380,
        genres: ['Fiction', 'Social', 'Drama'],
        description: 'Seto Dharti depicts the life of a child widow in Nepal, exploring themes of tradition, pain, and resilience.',
        excerpt: 'The white saree was not just a piece of cloth; it was a shroud for my dreams...',
        publishDate: '2012-03-01',
        publisher: 'FinePrint',
        pages: 380,
        isbn: '978-9937856414',
        tags: ['Madan Puraskar', 'Social Issue', 'Women'],
        isBestseller: true,
        isNew: false,
        mood: ['Melancholic', 'Reflective', 'Inspiring'],
    },
    {
        id: '5',
        title: 'Sirish Ko Phool',
        author: 'Parijat',
        coverUrl: '/books/sirish-ko-phool.png',
        rating: 4.5,
        reviewCount: 11200,
        price: { hardcover: 400, paperback: 250, ebook: 100 },
        formats: ['hardcover', 'paperback', 'ebook'],
        readingTime: 150,
        genres: ['Fiction', 'Philosophy', 'Existentialism'],
        description: 'Sirish Ko Phool (Blue Mimosa) is a masterpiece of Nepali literature, exploring the absurdity of life and human existence.',
        excerpt: 'Sakambari, why do you look at the Blue Mimosa with such intensity?',
        publishDate: '1964-01-01',
        publisher: 'Sajha Prakashan',
        pages: 120,
        isbn: '978-9993320215',
        tags: ['Classic', 'Existential', 'Masterpiece'],
        isBestseller: true,
        isNew: false,
        mood: ['Contemplative', 'Dark', 'Philosophical'],
    },
    {
        id: '6',
        title: 'China Harayeko Manche',
        author: 'Hari Bansha Acharya',
        coverUrl: '/books/china-harayeko-manche.png',
        rating: 4.8,
        reviewCount: 25000,
        price: { hardcover: 600, paperback: 450, ebook: 200 },
        formats: ['hardcover', 'paperback', 'ebook'],
        readingTime: 300,
        genres: ['Autobiography', 'Memoir', 'Humor'],
        description: 'The autobiography of Nepal\'s most beloved comedian, Hari Bansha Acharya, detailing his life, struggles, and journey to stardom.',
        excerpt: 'I was a man who had lost his china (mark)...',
        publishDate: '2013-01-01',
        publisher: 'FinePrint',
        pages: 300,
        isbn: '978-9937866659',
        tags: ['Bestseller', 'Biography', 'Inspiring'],
        isBestseller: true,
        isNew: false,
        mood: ['Joyful', 'Emotional', 'Inspiring'],
    },
    {
        id: '7',
        title: 'Jiwan Kada Ki Phool',
        author: 'Jhamak Ghimire',
        coverUrl: '/books/jiwan-kada-ki-phool.png',
        rating: 4.9,
        reviewCount: 18000,
        price: { hardcover: 550, paperback: 350, ebook: 150 },
        formats: ['hardcover', 'paperback', 'ebook'],
        readingTime: 250,
        genres: ['Autobiography', 'Literature', 'Inspirational'],
        description: 'An inspiring autobiography of Jhamak Ghimire, a writer born with cerebral palsy who wrote this masterpiece with her foot.',
        excerpt: 'Is life a thorn or a flower?',
        publishDate: '2010-01-01',
        publisher: 'Sajha Prakashan',
        pages: 250,
        isbn: '978-9993320628',
        tags: ['Madan Puraskar', 'Inspirational', 'Must Read'],
        isBestseller: true,
        isNew: false,
        mood: ['Inspiring', 'Emotional', 'Hopeful'],
    },
    {
        id: '8',
        title: 'Radha',
        author: 'Krishna Dharabasi',
        coverUrl: '/books/radha.png',
        rating: 4.6,
        reviewCount: 14000,
        price: { hardcover: 650, paperback: 450, ebook: 250 },
        formats: ['hardcover', 'paperback', 'ebook'],
        readingTime: 320,
        genres: ['Fiction', 'Mythology', 'Postmodern'],
        description: 'A postmodern retelling of the Radha-Krishna mythology, focusing on Radha\'s perspective and her waiting.',
        excerpt: 'Krishna, you are the world to everyone, but for me, you are just my Krishna...',
        publishDate: '2005-01-01',
        publisher: 'Pairavi Prakashan',
        pages: 350,
        isbn: '978-9993320550',
        tags: ['Madan Puraskar', 'Mythology', 'Love'],
        isBestseller: true,
        isNew: false,
        mood: ['Romantic', 'Philosophical', 'Melancholic'],
    },
    {
        id: '9',
        title: 'Summer Love',
        author: 'Subin Bhattarai',
        coverUrl: '/books/summer-love.png',
        rating: 4.4,
        reviewCount: 30000,
        price: { hardcover: 500, paperback: 350, ebook: 150 },
        formats: ['hardcover', 'paperback', 'ebook'],
        readingTime: 200,
        genres: ['Romance', 'Young Adult', 'Fiction'],
        description: 'A modern love story that captured the hearts of Nepali youth, following the journey of Atit and Saaya.',
        excerpt: 'Love happens only once, the rest is just life...',
        publishDate: '2012-12-01',
        publisher: 'FinePrint',
        pages: 280,
        isbn: '978-9937866628',
        tags: ['Bestseller', 'Romance', 'Youth'],
        isBestseller: true,
        isNew: false,
        mood: ['Romantic', 'Emotional', 'Nostalgic'],
    },
    {
        id: '10',
        title: 'Pagal Basti',
        author: 'Saru Bhakta',
        coverUrl: '/books/pagal-basti.png',
        rating: 4.7,
        reviewCount: 9500,
        price: { hardcover: 450, paperback: 300, ebook: 150 },
        formats: ['hardcover', 'paperback', 'ebook'],
        readingTime: 220,
        genres: ['Fiction', 'Philosophy', 'Drama'],
        description: 'A narrative set in Ghandruk, exploring the psyche of the characters and the concept of madness.',
        excerpt: 'In this settlement of madmen, who is truly sane?',
        publishDate: '1991-01-01',
        publisher: 'Sajha Prakashan',
        pages: 230,
        isbn: '978-9993320116',
        tags: ['Madan Puraskar', 'Classic', 'Psychological'],
        isBestseller: true,
        isNew: false,
        mood: ['Contemplative', 'Mysterious', 'Dark'],
    },
];

// Generate 95 more books programmatically with Nepali context
const additionalTitles = [
    'Summer Love', 'Saaya', 'China Harayeko Manche', 'Jiwan Kada Ki Phool', 'Radha',
    'Pagalbasti', 'Ghumne Mechmathi Andho Manche', 'Khushi', 'Damini Bhir', 'Loo',
    'Karodau Kasturi', 'Firfire', 'Yogmaya', 'Ranahar', 'Maharani',
    'Ek Sarko Maya', 'Priya Sufi', 'Singha Durbar', 'Langada Ko Sathi', 'Basain'
];

const nepaliAuthors = [
    'Subin Bhattarai', 'Hari Bansha Acharya', 'Jhamak Ghimire', 'Krishna Dharabasi',
    'Saru Bhakta', 'Bhupi Sherchan', 'Vijay Kumar', 'Rajan Mukarung', 'Nayan Raj Pandey',
    'Amar Neupane', 'Buddhisagar', 'Neelam Karki Niharika', 'Yogesh Raj', 'Chandra Prakash Baniya'
];

// Simple deterministic random number generator
const seededRandom = (seed: number) => {
    const x = Math.sin(seed++) * 10000;
    return x - Math.floor(x);
};

const LOCAL_COVERS = [
    '/books/muna-madan.png',
    '/books/palpasa-cafe.png',
    '/books/karnali-blues.png',
    '/books/seto-dharti.png',
    '/books/sirish-ko-phool.png',
    '/books/china-harayeko-manche.png',
    '/books/jiwan-kada-ki-phool.png',
    '/books/radha.png',
    '/books/summer-love.png',
    '/books/pagal-basti.png'
];

for (let i = 0; i < 95; i++) {
    const seed = i + 100; // Base seed
    const random = (offset: number) => seededRandom(seed + offset);
    const randomCover = LOCAL_COVERS[Math.floor(random(20) * LOCAL_COVERS.length)];
    const titleIndex = i % additionalTitles.length;
    const authorIndex = i % nepaliAuthors.length;

    MOCK_BOOKS.push({
        id: `${i + 11}`,
        title: additionalTitles[titleIndex],
        author: nepaliAuthors[authorIndex],
        coverUrl: randomCover,
        rating: 3.5 + random(1) * 1.5,
        reviewCount: Math.floor(random(2) * 50000),
        price: {
            hardcover: 500 + Math.floor(random(3) * 1000),
            paperback: 300 + Math.floor(random(4) * 500),
            ebook: 100 + Math.floor(random(5) * 300),
            audiobook: random(6) > 0.3 ? 0 : undefined,
        },
        formats: ['hardcover', 'paperback', 'ebook', random(7) > 0.3 ? 'audiobook' : 'paperback'] as any,
        readingTime: Math.floor(120 + random(8) * 400),
        genres: [GENRES[Math.floor(random(9) * GENRES.length)], GENRES[Math.floor(random(10) * GENRES.length)]],
        description: 'A captivating story from the heart of Nepal.',
        excerpt: 'The mountains whispered secrets that only the wind could understand...',
        publishDate: `20${15 + Math.floor(random(11) * 10)}-0${1 + Math.floor(random(12) * 9)}-${10 + Math.floor(random(13) * 18)}`,
        publisher: ['FinePrint', 'Nepalaya', 'Sajha Prakashan', 'Ratna Pustak Bhandar'][Math.floor(random(14) * 4)],
        pages: 200 + Math.floor(random(15) * 500),
        tags: ['Bestseller', 'Nepali Literature', 'Award Winner'].slice(0, Math.floor(random(16) * 3) + 1),
        isBestseller: random(17) > 0.7,
        isNew: random(18) > 0.8,
        mood: MOODS.slice(0, Math.floor(random(19) * 4) + 1).map(m => m.name),
    });
}
