-- Seed data for Nepali books
-- Run this in your Supabase SQL Editor to populate the database

INSERT INTO books (
    title, author, cover_url, rating, review_count, 
    price_hardcover, price_paperback, price_ebook, price_audiobook,
    formats, reading_time, genres, description, excerpt,
    publish_date, publisher, pages, isbn, tags,
    is_bestseller, is_new, mood
) VALUES 
(
    'Muna Madan',
    'Laxmi Prasad Devkota',
    'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400&h=600&fit=crop',
    4.9,
    15420,
    500, 350, 150, 100,
    ARRAY['hardcover', 'paperback', 'ebook', 'audiobook'],
    120,
    ARRAY['Poetry', 'Tragedy', 'Romance'],
    'Muna Madan is a short epic narrative poem by Laxmi Prasad Devkota. It is one of the most popular works in Nepali literature.',
    'Ishwar taila banayera, ke garyou manchhe lai? Ke garyou manchhe lai? ...',
    '1936-01-01',
    'Sajha Prakashan',
    60,
    '978-9937209876',
    ARRAY['Classic', 'Poetry', 'Must Read'],
    true,
    false,
    ARRAY['Melancholic', 'Romantic', 'Inspiring']
),
(
    'Palpasa Cafe',
    'Narayan Wagle',
    'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop',
    4.7,
    8924,
    800, 550, 300, null,
    ARRAY['hardcover', 'paperback', 'ebook'],
    350,
    ARRAY['Fiction', 'Historical', 'War'],
    'Palpasa Cafe tells the story of an artist, Drishya, during the height of the Nepali Civil War. It explores the effects of the war on ordinary people.',
    'Drishya sat in the cafe, watching the rain wash away the dust of Kathmandu...',
    '2005-01-01',
    'Nepalaya',
    245,
    '978-9937802107',
    ARRAY['Civil War', 'Art', 'Bestseller'],
    true,
    false,
    ARRAY['Contemplative', 'Melancholic', 'Reflective']
),
(
    'Karnali Blues',
    'Buddhisagar',
    'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&h=600&fit=crop',
    4.8,
    12500,
    750, 450, 250, null,
    ARRAY['hardcover', 'paperback', 'ebook'],
    400,
    ARRAY['Fiction', 'Coming of Age', 'Regional'],
    'Karnali Blues is a story about a young boy''s relationship with his father, set against the backdrop of the Karnali region.',
    'My father''s face is like a map of Karnali...',
    '2010-08-01',
    'FinePrint',
    400,
    '978-9937828855',
    ARRAY['Fatherhood', 'Regional', 'Touching'],
    true,
    false,
    ARRAY['Nostalgic', 'Emotional', 'Hopeful']
),
(
    'Seto Dharti',
    'Amar Neupane',
    'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop',
    4.6,
    9800,
    650, 400, 200, null,
    ARRAY['hardcover', 'paperback', 'ebook'],
    380,
    ARRAY['Fiction', 'Social', 'Drama'],
    'Seto Dharti depicts the life of a child widow in Nepal, exploring themes of tradition, pain, and resilience.',
    'The white saree was not just a piece of cloth; it was a shroud for my dreams...',
    '2012-03-01',
    'FinePrint',
    380,
    '978-9937856414',
    ARRAY['Madan Puraskar', 'Social Issue', 'Women'],
    true,
    false,
    ARRAY['Melancholic', 'Reflective', 'Inspiring']
),
(
    'Sirish Ko Phool',
    'Parijat',
    'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop',
    4.5,
    11200,
    400, 250, 100, null,
    ARRAY['hardcover', 'paperback', 'ebook'],
    150,
    ARRAY['Fiction', 'Philosophy', 'Existentialism'],
    'Sirish Ko Phool (Blue Mimosa) is a masterpiece of Nepali literature, exploring the absurdity of life and human existence.',
    'Sakambari, why do you look at the Blue Mimosa with such intensity?',
    '1964-01-01',
    'Sajha Prakashan',
    120,
    '978-9993320215',
    ARRAY['Classic', 'Existential', 'Masterpiece'],
    true,
    false,
    ARRAY['Contemplative', 'Dark', 'Philosophical']
),
(
    'China Harayeko Manche',
    'Hari Bansha Acharya',
    'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop',
    4.8,
    25000,
    600, 450, 200, null,
    ARRAY['hardcover', 'paperback', 'ebook'],
    300,
    ARRAY['Autobiography', 'Memoir', 'Humor'],
    'The autobiography of Nepal''s most beloved comedian, Hari Bansha Acharya, detailing his life, struggles, and journey to stardom.',
    'I was a man who had lost his china (mark)...',
    '2013-01-01',
    'FinePrint',
    300,
    '978-9937866659',
    ARRAY['Bestseller', 'Biography', 'Inspiring'],
    true,
    false,
    ARRAY['Joyful', 'Emotional', 'Inspiring']
),
(
    'Jiwan Kada Ki Phool',
    'Jhamak Ghimire',
    'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=400&h=600&fit=crop',
    4.9,
    18000,
    550, 350, 150, null,
    ARRAY['hardcover', 'paperback', 'ebook'],
    250,
    ARRAY['Autobiography', 'Literature', 'Inspirational'],
    'An inspiring autobiography of Jhamak Ghimire, a writer born with cerebral palsy who wrote this masterpiece with her foot.',
    'Is life a thorn or a flower?',
    '2010-01-01',
    'Sajha Prakashan',
    250,
    '978-9993320628',
    ARRAY['Madan Puraskar', 'Inspirational', 'Must Read'],
    true,
    false,
    ARRAY['Inspiring', 'Emotional', 'Hopeful']
),
(
    'Radha',
    'Krishna Dharabasi',
    'https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=400&h=600&fit=crop',
    4.6,
    14000,
    650, 450, 250, null,
    ARRAY['hardcover', 'paperback', 'ebook'],
    320,
    ARRAY['Fiction', 'Mythology', 'Postmodern'],
    'A postmodern retelling of the Radha-Krishna mythology, focusing on Radha''s perspective and her waiting.',
    'Krishna, you are the world to everyone, but for me, you are just my Krishna...',
    '2005-01-01',
    'Pairavi Prakashan',
    350,
    '978-9993320550',
    ARRAY['Madan Puraskar', 'Mythology', 'Love'],
    true,
    false,
    ARRAY['Romantic', 'Philosophical', 'Melancholic']
),
(
    'Summer Love',
    'Subin Bhattarai',
    'https://images.unsplash.com/photo-1474932430478-367dbb6832c1?w=400&h=600&fit=crop',
    4.4,
    30000,
    500, 350, 150, null,
    ARRAY['hardcover', 'paperback', 'ebook'],
    200,
    ARRAY['Romance', 'Young Adult', 'Fiction'],
    'A modern love story that captured the hearts of Nepali youth, following the journey of Atit and Saaya.',
    'Love happens only once, the rest is just life...',
    '2012-12-01',
    'FinePrint',
    280,
    '978-9937866628',
    ARRAY['Bestseller', 'Romance', 'Youth'],
    true,
    false,
    ARRAY['Romantic', 'Emotional', 'Nostalgic']
),
(
    'Pagal Basti',
    'Saru Bhakta',
    'https://images.unsplash.com/photo-1518373714866-3f1478910cc0?w=400&h=600&fit=crop',
    4.7,
    9500,
    450, 300, 150, null,
    ARRAY['hardcover', 'paperback', 'ebook'],
    220,
    ARRAY['Fiction', 'Philosophy', 'Drama'],
    'A narrative set in Ghandruk, exploring the psyche of the characters and the concept of madness.',
    'In this settlement of madmen, who is truly sane?',
    '1991-01-01',
    'Sajha Prakashan',
    230,
    '978-9993320116',
    ARRAY['Madan Puraskar', 'Classic', 'Psychological'],
    true,
    false,
    ARRAY['Contemplative', 'Mysterious', 'Dark']
);
